export const ACTOR_NEW_KEYWORDS = 'ACTOR_NEW_KEYWORDS';
export const ACTOR_SEARCH_REQUEST = 'ACTOR_SEARCH_REQUEST';
export const ACTOR_SEARCH_SUCCESS = 'ACTOR_SEARCH_SUCCESS';
export const ACTOR_SEARCH_FAIL = 'ACTOR_SEARCH_FAIL';
export const ACTOR_DETAILS_REQUEST = 'ACTOR_DETAILS_REQUEST';
export const ACTOR_DETAILS_SUCCESS = 'ACTOR_DETAILS_SUCCESS';
export const ACTOR_DETAILS_FAIL = 'ACTOR_DETAILS_FAIL';
