export const MOVIE_NEW_KEYWORDS = 'MOVIE_NEW_KEYWORDS';
export const MOVIE_SEARCH_REQUEST = 'MOVIE_SEARCH_REQUEST';
export const MOVIE_SEARCH_SUCCESS = 'MOVIE_SEARCH_SUCCESS';
export const MOVIE_SEARCH_FAIL = 'MOVIE_SEARCH_FAIL';
export const MOVIE_DETAILS_REQUEST = 'MOVIE_DETAILS_REQUEST';
export const MOVIE_DETAILS_SUCCESS = 'MOVIE_DETAILS_SUCCESS';
export const MOVIE_DETAILS_FAIL = 'MOVIE_DETAILS_FAIL';
